/* Simplified Chinese for the Five Elements Acupuncture page (used by js/acupuncture-zh.js).
   Keys are the English text exactly as shown on the page. */
window.MMC_ACU_ZH = {
    "Home": "首页",
    "Five Elements Acupuncture": "五行针灸",
    "Five Elements Acupuncture & Wellness": "五行针灸与健康中心",
    "Licensed acupuncture, Chinese medicine, and pain management in Gaithersburg, MD — personalized care for pain, stress, fertility, and chronic conditions.": "位于马里兰州盖瑟斯堡的执业针灸、中医与疼痛管理服务——为疼痛、压力、生育及慢性病提供个性化调理。",
    "Services": "服务项目",
    "Conditions": "主治病症",
    "Care Journey": "诊疗流程",
    "Preparation": "就诊准备",
    "Provider": "医师介绍",
    "Insurance": "保险",
    "FAQ": "常见问题",
    "Traditional Wisdom · Modern Care": "传统智慧 · 现代医疗",
    "Welcome to Five Elements Acupuncture & Wellness": "欢迎来到<span class=\"up-accent\">五行</span>针灸<br>与健康中心",
    "Experience the healing power of traditional Chinese medicine combined with modern functional health care. Dr. Min Lu provides personalized acupuncture treatments and holistic wellness solutions to help you achieve optimal health.": "体验传统中医与现代功能医学相结合的疗愈力量。路敏医师为您提供个性化的针灸治疗和整体健康方案，帮助您达到最佳健康状态。",
    "Holistic Healing": "整体调理",
    "Personalized Care": "个性化诊疗",
    "Whole-Body Wellness": "全身健康",
    "Book Online": "在线预约",
    "Call (301) 709-4551": "致电 (301) 709-4551",
    "Our Acupuncture Services": "针灸服务项目",
    "At Five Elements Acupuncture & Wellness, Dr. Lu provides a wide range of acupuncture and Chinese medicine services, including cupping therapy, moxibustion, massage therapy, and stress management to help you achieve optimal wellness.": "在五行针灸与健康中心，路医师提供全面的针灸与中医服务，包括拔罐、艾灸、推拿按摩及压力管理，帮助您达到最佳健康状态。",
    "Pain Management": "疼痛管理",
    "Acupuncture therapy for chronic and acute pain relief": "针灸治疗，缓解慢性及急性疼痛",
    "Massage Therapy": "推拿按摩",
    "Therapeutic massage for relaxation and pain relief": "治疗性按摩，放松身心、缓解疼痛",
    "Stress Management": "压力管理",
    "Acupuncture and holistic approaches to reduce stress": "以针灸及整体疗法舒缓压力",
    "Insomnia": "失眠",
    "Acupuncture treatment for sleep disorders": "针灸调理睡眠障碍",
    "Cupping Therapy": "拔罐疗法",
    "Ancient technique combined with acupuncture": "古老疗法，与针灸相结合",
    "Moxibustion": "艾灸",
    "Heat therapy to enhance acupuncture treatment": "温热疗法，增强针灸疗效",
    "Fertility": "助孕调理",
    "Acupuncture for fertility and reproductive health": "针灸助孕与生殖健康调理",
    "Digestive Health": "消化健康",
    "Acupuncture for digestive disorders and wellness": "针灸调理消化系统疾病",
    "Conditions We Treat": "主治病症",
    "Dr. Lu provides specialized care for a wide range of conditions, combining traditional Chinese medicine with modern functional health practices.": "路医师结合传统中医与现代功能医学，为多种病症提供专业诊疗。",
    "Women's Health": "妇科调理",
    "Infertility & Ovarian Dysfunction": "不孕症及卵巢功能失调",
    "Polycystic Ovary Syndrome (PCOS)": "多囊卵巢综合征（PCOS）",
    "Menstrual Disease & Irregular Periods": "月经病及月经不调",
    "Menopausal Syndrome": "更年期综合征",
    "Pelvic Inflammatory Disease": "盆腔炎",
    "Vulva Leukoplakia": "外阴白斑",
    "Postnatal Care": "产后调养",
    "General Health Conditions": "常见健康问题",
    "Depression & Anxiety": "抑郁与焦虑",
    "Insomnia & Sleep Disorders": "失眠及睡眠障碍",
    "Allergies & Respiratory Issues": "过敏及呼吸系统问题",
    "Pain Management (Chronic & Acute)": "疼痛管理（慢性及急性）",
    "Digestive Disorders": "消化系统疾病",
    "Stress & Fatigue": "压力与疲劳",
    "Experience High-Quality Holistic Acupuncture Care": "体验高品质的整体针灸诊疗",
    "To receive high-quality holistic health care in a warm and welcoming environment, partner with Dr. Lu. Make an appointment at Five Elements Acupuncture & Wellness for professional acupuncture treatment by calling the office or booking online today.": "在温馨舒适的环境中获得高品质的整体健康调理——欢迎与路医师携手。今天就致电诊所或在线预约五行针灸与健康中心的专业针灸治疗。",
    "Personalized Acupuncture Care Journey": "个性化针灸诊疗流程",
    "Every acupuncture visit begins with thoughtful listening, collaborative goal-setting, and a tailored treatment plan that integrates traditional Chinese medicine, bodywork, and lifestyle guidance for lasting wellness.": "每次针灸就诊都从耐心倾听、共同设定目标开始，并制定融合传统中医、身体疗法与生活方式指导的个性化方案，助您长久保持健康。",
    "01": "01", "02": "02", "03": "03", "04": "04",
    "Comprehensive Consultation": "全面问诊",
    "Dr. Lu performs a detailed health history, pulse reading, and tongue analysis to understand the root imbalances before beginning your acupuncture session.": "针灸治疗开始前，路医师会详细了解您的病史，并通过把脉和舌诊找出失衡的根源。",
    "Targeted Acupuncture Therapy": "精准针灸治疗",
    "Precise acupuncture point selection, gentle needling, and supportive modalities like moxibustion or cupping amplify circulation, reduce pain, and restore energy flow.": "精准选穴、轻柔施针，并辅以艾灸或拔罐等疗法，促进血液循环、减轻疼痛、恢复气血运行。",
    "Integrative Support": "综合辅助调理",
    "Sessions may include herbal guidance, massage therapy, or stress management tools that complement acupuncture and help you maintain balance between visits.": "治疗中可能包括中草药指导、推拿按摩或压力管理方法，与针灸相辅相成，帮助您在两次就诊之间保持身体平衡。",
    "Ongoing Wellness Planning": "持续健康规划",
    "Regular acupuncture follow-ups, personalized nutrition tips, and movement recommendations keep your wellness plan actionable and aligned with your lifestyle.": "定期针灸复诊、个性化营养建议和运动指导，让您的健康计划切实可行，并与您的生活方式相契合。",
    "Preparing for Your Acupuncture Treatment": "针灸治疗前的准备",
    "Simple habits before and after each acupuncture appointment help you feel relaxed, supported, and ready to embrace the healing process Dr. Lu designs for you.": "每次针灸前后养成一些简单的习惯，能让您更加放松安心，更好地配合路医师为您设计的疗愈过程。",
    "Before Your Session": "治疗前",
    "Enjoy a light, nourishing meal and arrive hydrated to support acupuncture circulation.": "就诊前请适量进食清淡营养的餐点，并补充充足水分，以利于针灸时的气血运行。",
    "Wear comfortable clothing that can easily be rolled to access acupuncture points on the arms and legs.": "请穿着舒适、袖口和裤腿易于卷起的衣物，方便在手臂和腿部取穴。",
    "During Treatment": "治疗中",
    "Settle into a quiet, spa-like environment while Dr. Lu places acupuncture needles with precision and care.": "在安静、如水疗般舒适的环境中放松身心，由路医师精准细致地为您施针。",
    "Experience complementary therapies such as cupping therapy, moxibustion, or massage therapy when appropriate.": "必要时可配合拔罐、艾灸或推拿按摩等辅助疗法。",
    "Aftercare Tips": "治疗后须知",
    "Drink water, rest, and notice how your body responds as the acupuncture session continues to work.": "治疗后请多喝水、注意休息，并留意身体的反应——针灸的作用会在治疗后持续发挥。",
    "Follow the customized acupuncture care plan, including herbal medicine and gentle exercises between visits.": "请遵循个性化的针灸调理方案，包括在两次就诊之间服用中草药和进行舒缓运动。",
    "Your acupuncturist": "您的针灸医师",
    "Meet Dr. Min Lu | 路敏医师简介": "路敏医师简介",
    "Dr. Min Lu is a licensed acupuncturist dedicated to providing exceptional acupuncture care tailored to your unique health needs, integrating traditional Chinese medicine with modern biomedical knowledge.": "路敏医师是一位执业针灸师，致力于根据您独特的健康需求提供卓越的针灸诊疗，融合传统中医与现代生物医学知识。",
    "Coverage": "保险覆盖",
    "Insurance & Payment Options": "保险与付款方式",
    "We accept most insurance providers.": "我们接受大多数保险公司的保险。",
    "View accepted plans": "查看接受的保险计划",
    "Auto & personal injury": "车险与人身伤害险",
    "We also accept auto and personal injury insurance for acupuncture treatments.": "针灸治疗也接受车险及人身伤害保险。",
    "Questions about your coverage": "保险覆盖咨询",
    "If you have specific questions regarding your coverage for acupuncture services, please contact us for additional information.": "如对针灸服务的保险覆盖范围有具体疑问，请联系我们了解详情。",
    "Frequently Asked Questions": "常见问题",
    "Common questions about acupuncture at Montgomery Medical Clinic.": "关于 Montgomery Medical Clinic 针灸服务的常见问题。",
    "Still have a question?": "还有其他问题？",
    "Call (301) 208-2273": "致电 (301) 208-2273",
    "or": "或",
    "text us": "发短信给我们",
    ".": "。",
    "What conditions can acupuncture treat?": "针灸可以治疗哪些病症？",
    "Acupuncture is recognized by the World Health Organization (WHO) and the National Institutes of Health (NIH) as an effective treatment for a wide range of conditions, including:": "针灸已被<strong class=\"text-gray-800\">世界卫生组织（WHO）</strong>和<strong class=\"text-gray-800\">美国国立卫生研究院（NIH）</strong>认可为多种病症的有效疗法，包括：",
    "● Pain management — chronic pain, migraines, tension headaches, sciatica, back pain, neck pain, and shoulder pain": "● 疼痛管理——慢性疼痛、偏头痛、紧张性头痛、坐骨神经痛、腰背痛、颈痛及肩痛",
    "● Musculoskeletal — arthritis, joint stiffness, fibromyalgia, carpal tunnel syndrome, and sports injuries": "● 肌肉骨骼——关节炎、关节僵硬、纤维肌痛、腕管综合征及运动损伤",
    "● Mental health — stress, anxiety, depression, PTSD, and insomnia": "● 心理健康——压力、焦虑、抑郁、创伤后应激障碍（PTSD）及失眠",
    "● Digestive health — IBS, acid reflux, nausea, bloating, and appetite regulation": "● 消化健康——肠易激综合征（IBS）、胃酸反流、恶心、腹胀及食欲调节",
    "● Women’s health — fertility support, menstrual irregularities, menopause symptoms, and pregnancy-related discomfort": "● 妇科健康——助孕、月经不调、更年期症状及孕期不适",
    "● Respiratory & allergies — seasonal allergies, sinusitis, and asthma support": "● 呼吸与过敏——季节性过敏、鼻窦炎及哮喘辅助治疗",
    "During your first visit, Dr. Min Lu will perform a comprehensive evaluation and create a personalized treatment plan tailored to your specific health goals.": "首次就诊时，路敏医师会为您进行全面评估，并根据您的具体健康目标制定个性化治疗方案。",
    "Does acupuncture hurt?": "针灸会痛吗？",
    "Most patients feel little to no pain. Acupuncture needles are hair-thin — about 0.2 mm in diameter, which is 25–50 times thinner than a standard hypodermic needle used for injections or blood draws.": "大多数患者几乎感觉不到疼痛。针灸针细如发丝——直径约 0.2 毫米，比打针或抽血用的普通注射针细 25 至 50 倍。",
    "You may feel a slight tingling, warmth, or mild pressure at the insertion point — this is known as “de qi,” a sign that the treatment is activating your body’s natural healing response. Many patients find the sessions so relaxing that they fall asleep during treatment.": "进针处可能会有轻微的麻、热或胀感——这就是“得气”，说明治疗正在激发身体的自然愈合反应。许多患者觉得治疗过程非常放松，甚至在治疗中睡着。",
    "Dr. Min Lu uses gentle, precise needle techniques refined over years of clinical practice to ensure your comfort throughout every session.": "路敏医师运用多年临床实践中精炼出的轻柔、精准的针法，确保您在每次治疗中都感到舒适。",
    "Do I need an appointment, or do you accept walk-ins?": "需要预约吗？可以直接上门就诊吗？",
    "Both! Montgomery Medical Clinic accepts walk-ins 7 days a week and also offers scheduled appointments for your convenience.": "两者皆可！Montgomery Medical Clinic 每周 7 天接受无预约就诊，也可提前预约，方便您安排时间。",
    "● Walk-ins welcome — seen on a first-come, first-served basis during regular clinic hours": "● 欢迎直接就诊——在正常门诊时间内按先到先诊的顺序安排",
    "● Same-day appointments — book online for the shortest wait time": "● 当日预约——在线预约，候诊时间最短",
    "● Scheduled appointments — reserve your preferred date and time in advance": "● 提前预约——预先选定您方便的日期和时间",
    "For the fastest service, we recommend booking a same-day appointment online or calling us at": "如需最快获得服务，建议您在线预约当日门诊，或致电",
    "(301) 208-2273": "(301) 208-2273",
    ". Our clinic is conveniently located in": "。我们的诊所位于交通便利的",
    "Gaithersburg, MD": "马里兰州盖瑟斯堡",
    "and serves patients throughout Montgomery County.": "，服务蒙哥马利县各地的患者。",
    "Does insurance cover acupuncture?": "保险涵盖针灸吗？",
    "Many insurance plans now provide coverage for acupuncture, especially following Medicare’s 2020 decision to cover acupuncture for chronic low back pain. Private insurers including Aetna, Blue Cross Blue Shield, Cigna, and UnitedHealthcare increasingly cover acupuncture benefits as well.": "如今许多保险计划都涵盖针灸，尤其是 Medicare 自 2020 年起将针灸纳入慢性下背痛的报销范围之后。Aetna、Blue Cross Blue Shield、Cigna 和 UnitedHealthcare 等私人保险公司也越来越多地提供针灸福利。",
    "Coverage details vary by provider and plan, so we recommend verifying your benefits before your first visit. Our front desk team is happy to help — call": "具体覆盖范围因保险公司和计划而异，建议您在首次就诊前确认您的保险福利。我们的前台团队乐意为您提供帮助——请致电",
    "(301) 709-4551": "(301) 709-4551",
    "and we can assist with insurance questions and out-of-pocket cost estimates.": "，我们可协助解答保险问题并估算自付费用。",
    "How many acupuncture sessions will I need?": "需要做几次针灸？",
    "The number of sessions depends on your condition, its severity, and how your body responds to treatment:": "所需疗程取决于您的病情、严重程度以及身体对治疗的反应：",
    "● Acute issues (recent injuries, headaches, muscle tension) — may improve noticeably in 3–5 sessions": "● 急性问题（新近受伤、头痛、肌肉紧张）——通常 3 至 5 次即可明显改善",
    "● Chronic conditions (long-term pain, digestive disorders, anxiety) — typically benefit from 8–12 sessions": "● 慢性病症（长期疼痛、消化系统疾病、焦虑）——一般需要 8 至 12 次",
    "● Wellness maintenance (stress relief, immune support, preventive care) — monthly or bi-monthly sessions recommended": "● 日常保健（缓解压力、增强免疫、预防保健）——建议每月一次或每两个月一次",
    "Many patients report feeling improvement after their very first session. Dr. Min Lu will create a personalized treatment schedule during your initial consultation and adjust it as your condition progresses.": "许多患者在第一次治疗后就感到有所改善。路敏医师会在初诊时为您制定个性化疗程，并根据病情进展进行调整。",
    "What other services does Five Elements Acupuncture offer besides needling?": "除针刺外，五行针灸还提供哪些服务？",
    "Five Elements Acupuncture at Montgomery Medical Clinic offers a full range of traditional Chinese medicine (TCM) therapies, including:": "Montgomery Medical Clinic 的五行针灸提供全面的传统中医疗法，包括：",
    "● Cupping therapy — uses suction cups to relieve muscle tension, improve blood flow, and reduce inflammation": "● 拔罐疗法——利用负压罐缓解肌肉紧张、促进血液循环、减轻炎症",
    "● Moxibustion — a warming technique that stimulates acupuncture points to boost circulation and immunity": "● 艾灸——以温热刺激穴位，促进血液循环、增强免疫力",
    "● Herbal medicine consultations — custom herbal formulas prescribed to complement your acupuncture treatments": "● 中草药咨询——开具个性化草药方剂，配合针灸治疗",
    "● Fertility acupuncture — specialized protocols to support natural conception and IVF treatments": "● 助孕针灸——专门方案，辅助自然受孕及试管婴儿（IVF）治疗",
    "● Electroacupuncture — gentle electrical stimulation paired with needles for enhanced pain relief and nerve regeneration": "● 电针——在针刺基础上配合轻微电刺激，增强止痛效果并促进神经修复",
    "Dr. Min Lu may combine multiple modalities in a single session for a comprehensive, holistic treatment approach tailored to your needs.": "路敏医师可能在一次治疗中结合多种疗法，为您量身打造全面、整体的治疗方案。",
    "Ready to Begin Your Acupuncture Healing Journey?": "准备好开启您的针灸疗愈之旅了吗？",
    "Schedule your acupuncture consultation with Dr. Min Lu today and experience the benefits of traditional Chinese medicine and professional acupuncture care in Gaithersburg, MD.": "今天就预约路敏医师的针灸问诊，在马里兰州盖瑟斯堡体验传统中医与专业针灸诊疗带来的益处。"
};
